### ISSUE TITLE
Connecting with third party API

### ISSUE THREAD

**Issue by designloud** [JoeSz/WordPress-Plugin-Boilerplate-Tutorial#11]
First off, thank you for creating this.  I was lost when downloading the initial boilerplate but your fork helped me understand where to do things and I've made a lot of progress.

I wouldn't expect you to do the work for me but any guidance on what files to use would be very helpful.  I've created custom post types that really just sync information to and from a 3rd party API.   I can follow [this tutorial](https://webdesign.tutsplus.com/articles/how-to-incorporate-external-apis-in-your-wordpress-theme-or-plugin--cms-33542) for interacting with the API but which file(s) would I place this code so when new posts are added in my custom post type it sends it through the API and when things are created on the 3rd party app that they are created as posts in my custom post types?  ( I followed your tutorial on custom post types to get this far).

**Comment by JoeSz** [comment]
Hi,
for the tutorial: https://webdesign.tutsplus.com/articles/how-to-incorporate-external-apis-in-your-wordpress-theme-or-plugin--cms-33542

if you take a look here: https://github.com/tutsplus/widget-flickr
you can see, it is a class (you can put this in a new "widget" folder or in public or includes) which you can include in
includes/class-plugin-name.php load_dependencies function,
and three hooks. 
The "wp_enqueue_scripts" and "widgets_init" hooks going to the includes/class-plugin-name.php define_public_hooks function and the function to the public/class-plugin-name-public.php.

"so when new posts are added in my custom post type it sends it through the API"
You need to hook a function to the following hooks (maybe not all of them :) ):
(https://wordpress.stackexchange.com/questions/8257/add-action-hook-for-completely-new-post)
add_action('new_to_publish', 'your_function');
add_action('draft_to_publish', 'your_function');
add_action('pending_to_publish', 'your_function');
File to add this hooks:  includes/class-plugin-name.php
and the function probably in the admin/class-plugin-name-admin.php

"when things are created on the 3rd party app that they are created as posts in my custom post types"
I do not know, how the 3rd party app send information to you. Via POST, GET?
